### ISSUE TITLE
Incomplete sentence in copy on About page

### ISSUE THREAD

**Issue by danford1** [MuseumStat/imls-museum-data#150]
About page copy includes typo (incomplete sentence) in 3rd sentence in first paragraph:

"MuseumStat is a robust online resource to support museums, communities, and researchers in gaining insights into the reach of museums and the communities they serve. MuseumStat contains information on about 30,000 organizations in the Institute of Museum and Library Services’ Museum Universe Data File (MUDF). **The museum data are combined with community metrics on every U.S. census tract in the.** MuseumStat is built on a geographical information system (GIS) platform that is designed to be intuitive and useful to a wide range of users and will continue to grow in its scope of features and information."

**Comment by CloudNiner** [comment]
@nevillevak @jbranigan I will update this and deploy if you can provide replacement text for this first paragraph.

**Comment by nevillevak** [comment]
Thanks, Andrew.  The sentence in question should read (added text in red):

“…The museum data are combined with community metrics on every U.S. census tract in the United States..."



Best,
Neville
________________________________
Neville K. Vakharia
Assistant Professor and Research Director
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
215.571.4439, nvakharia@drexel.edu

Office Hours:
Tuesdays and Thursdays, 2:00 – 5:00
By appointment only
