### ISSUE TITLE
Use HTTPS Census API urls

### ISSUE THREAD

**Issue by CloudNiner** [MuseumStat/imls-museum-data#155]
The Census API is going HTTPS only on August 28, 2017. We should update the application to explicitly request HTTPS. In the meantime, their documentation states that a redirect will be in place, which our JS should respect.

**Comment by nevillevak** [comment]
Hi Andrew,

Thanks for letting us know. Let's discuss when we meet later in June.

Best,
Neville
___________________
Neville K. Vakharia
Assistant Professor and Research Director
Drexel University
Westphal College of Media Arts & Design
215.571.4439, nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>

On May 31, 2017, at 9:07 PM, Andrew Fink <notifications@github.com<mailto:notifications@github.com>> wrote:


The Census API is going HTTPS only on August 28, 2017. We should update the application to explicitly request HTTPS. In the meantime, their documentation states that a redirect will be in place, which our JS should respect.

**Comment by jcahail** [comment]
@CloudNiner - @nevillevak has approved this change. Let's be sure to put it in the next sprint.

**Comment by CloudNiner** [comment]
👍
